/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewSiswa;

import DataBase.DBConnection;
import Controller.PresensiController;
import Session.Session;
import Model.Presensi;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import scala.Int;
/**
 *
 * @author Axioo Pongo
 */
public class presensiDanKegiatan extends javax.swing.JFrame {
    private PresensiController controller;
    private int id_presensi;
    /**
     * Creates new form presensiDanKegiatan
     */
    public presensiDanKegiatan() {
        
        this.controller = new Controller.PresensiController();
        
        initComponents();
        
        btnKepulangan.setEnabled(false);
        tblPresensi.getSelectionModel().addListSelectionListener(e -> {
                if (!e.getValueIsAdjusting() && tblPresensi.getSelectedRow() != -1) {
                    int row = tblPresensi.getSelectedRow();
                    id_presensi = Integer.parseInt(tblPresensi.getValueAt(row, 0).toString());
                }
                cbStatus.setEnabled(false);
                tfKegiatan.setEnabled(false);
                btnKepulangan.setEnabled(true);
            });
        
        tampilkanDataKeTabel(Session.getId_siswa());
    }
    
    private void tampilkanDataKeTabel(int siswaId) {
    DefaultTableModel model = (DefaultTableModel) tblPresensi.getModel();
    model.setRowCount(0); // Bersihkan tabel

    String sql = "SELECT p.id, p.tanggal, p.status, p.jam_masuk, p.jam_keluar, p.keterangan " +
                 "FROM presensi p " +
                 "JOIN monitoring m ON p.Monitoring_id = m.id " +
                 "WHERE m.siswa_id = ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, siswaId);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            int id = rs.getInt(siswaId);
            String tanggal = rs.getString("tanggal");
            int statusCode = rs.getInt("status");
            String jamMasuk = rs.getString("jam_masuk");
            String jamKeluar = rs.getString("jam_keluar");
            String keterangan = rs.getString("keterangan");

            // Ubah status ke bentuk teks (misalnya: 0 = Alpha, 1 = Hadir, dll)
            String status = controller.statusPresensi(statusCode);

            model.addRow(new Object[]{id, tanggal, status, jamMasuk, jamKeluar, keterangan});
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPresensi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfKegiatan = new javax.swing.JTextArea();
        cbStatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnKepulangan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPresensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tanggal", "Status", "Jam masuk", "Jam keluar", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPresensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPresensiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPresensi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Isi Presensi Dan Kegiatan");

        tfKegiatan.setColumns(20);
        tfKegiatan.setRows(5);
        jScrollPane2.setViewportView(tfKegiatan);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0. Alpha", "1. Hadir", "2. Sakit", "3. Izin" }));

        jButton1.setText("Cancle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnKepulangan.setText("Kepulangan");
        btnKepulangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKepulanganActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKepulangan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addComponent(btnKepulangan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPresensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPresensiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPresensiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void resetForm(){
        tfKegiatan.setText("");
        cbStatus.setSelectedIndex(0);
    }
    
    public presensiDanKegiatan(PresensiController controller, int id_presensi, JButton btnKepulangan, JButton btnTambah, JComboBox<String> cbStatus, JButton jButton1, JLabel jLabel1, JScrollPane jScrollPane1, JScrollPane jScrollPane2, JTable tblPresensi, JTextArea tfKegiatan) throws HeadlessException {
        this.controller = controller;
        this.id_presensi = id_presensi;
        this.btnKepulangan = btnKepulangan;
        this.btnTambah = btnTambah;
        this.cbStatus = cbStatus;
        this.jButton1 = jButton1;
        this.jLabel1 = jLabel1;
        this.jScrollPane1 = jScrollPane1;
        this.jScrollPane2 = jScrollPane2;
        this.tblPresensi = tblPresensi;
        this.tfKegiatan = tfKegiatan;
    }

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String keterangan = tfKegiatan.getText();
        int status = cbStatus.getSelectedIndex();
        
        Presensi presensi = new Presensi();
        presensi.setKeterangan(keterangan);
        presensi.setStatus(status);
        presensi.setMonitoring_id(controller.getMonitoringIdBySiswaId(Session.getId_siswa()));
        
        PresensiController.masukkanDataPresensi(presensi);
        tampilkanDataKeTabel(Session.getId_siswa());
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKepulanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKepulanganActionPerformed
        // TODO add your handling code here:
        controller.setJamKeluar(id_presensi);
        tampilkanDataKeTabel(Session.getId_siswa());
    }//GEN-LAST:event_btnKepulanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presensiDanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presensiDanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presensiDanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presensiDanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presensiDanKegiatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKepulangan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPresensi;
    private javax.swing.JTextArea tfKegiatan;
    // End of variables declaration//GEN-END:variables
}
