/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewGuru;

import Controller.SiswaController;
import DataBase.DBConnection;
import Controller.MonitoringController;
import Session.Session;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import scala.Int;

/**
 *
 * @author Axioo Pongo
 */
public class MonotiringForGuru extends javax.swing.JFrame {
    
    private Session session;
    private MonitoringController controller;
    private int SiswaId;
    
    /**
     * Creates new form MonotiringForGuru
     */
    public MonotiringForGuru() {
        initComponents(); 
        int guruId = Session.getId_guru();
        
        tblMonitoringGuru.getSelectionModel().addListSelectionListener(e -> {
                if (!e.getValueIsAdjusting() && tblMonitoringGuru.getSelectedRow() != -1) {
                    int row = tblMonitoringGuru.getSelectedRow();
                    String nisn = tblMonitoringGuru.getValueAt(row, 1).toString();
                    SiswaId = MonitoringController.getIdSiswaByNisn(nisn);
                }
            });
        
        tampilDataKeTabel(guruId);
    }
    
    private void tampilDataKeTabel(int guruId) {
        DefaultTableModel model = (DefaultTableModel) tblMonitoringGuru.getModel();
        model.setRowCount(0); // Bersihkan tabel sebelum isi

        String sql = "SELECT s.id, s.nama, s.nisn, s.kelas, m.tanggal_mulai, m.tanggal_selesai, i.nama AS nama_instansi " +
                     "FROM monitoring m " +
                     "JOIN siswa s ON m.siswa_id = s.id " +
                     "JOIN instansi i ON m.instansi_id = i.id " +
                     "WHERE m.guru_id = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, guruId);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String nama = rs.getString("nama");
                String nisn = rs.getString("nisn");
                String kelas = rs.getString("kelas");
                String tanggal_mulai = rs.getString("tanggal_mulai");
                String tanggal_selesai = rs.getString("tanggal_selesai");
                String instansi = rs.getString("nama_instansi");
                SiswaId = rs.getInt("id");
                
                if(tanggal_mulai == null){
                    tanggal_mulai = "-";
                }
                if(tanggal_selesai == null){
                    tanggal_selesai = "-";
                }

                model.addRow(new Object[]{nama, nisn, kelas, tanggal_mulai, tanggal_selesai, instansi});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLihatPresensi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonitoringGuru = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bLihatPresensi.setText("Lihat presensi");
        bLihatPresensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLihatPresensiActionPerformed(evt);
            }
        });

        tblMonitoringGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama ", "Nisn", "Kelas", "Tanggal Mulai", "Tanggal Selesai", "Instansi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonitoringGuru.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblMonitoringGuruAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblMonitoringGuru);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Monitoring");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 726, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(bLihatPresensi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLihatPresensi)
                        .addGap(281, 281, 281))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLihatPresensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLihatPresensiActionPerformed
        new DetailPresensi(SiswaId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bLihatPresensiActionPerformed

    private void tblMonitoringGuruAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblMonitoringGuruAncestorAdded
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblMonitoringGuru.getModel();

        Object[] rowData = new Object[4];

        model.addRow(rowData);
    }//GEN-LAST:event_tblMonitoringGuruAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonotiringForGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonotiringForGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonotiringForGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonotiringForGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonotiringForGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLihatPresensi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMonitoringGuru;
    // End of variables declaration//GEN-END:variables
}
